## Tensorflow Basics

In [1]:
import tensorflow as tf

In [2]:
namaste = tf.constant("Namaste")

In [3]:
namaste

<tf.Tensor: shape=(), dtype=string, numpy=b'Namaste'>

In [4]:
type(namaste)

tensorflow.python.framework.ops.EagerTensor

In [5]:
num = tf.constant(101)

In [6]:
num

<tf.Tensor: shape=(), dtype=int32, numpy=101>

In [7]:
type(num)

tensorflow.python.framework.ops.EagerTensor

---

In [8]:
# Eager execution is enabled by default in TensorFlow 2.x
a = tf.constant(2)
b = tf.constant(3)
c = a + b

print(c)

tf.Tensor(5, shape=(), dtype=int32)


In [9]:
a.shape

TensorShape([])

In [10]:
import numpy as np

In [11]:
a = np.array([[5.0, 5.0]])
b = np.array([[2.0],[2.0]])

In [12]:
a

array([[5., 5.]])

In [13]:
b

array([[2.],
       [2.]])

In [14]:
a.shape

(1, 2)

In [15]:
b.shape

(2, 1)

In [16]:
mat1 = tf.constant(a)
mat2 = tf.constant(b)

In [17]:
mat1

<tf.Tensor: shape=(1, 2), dtype=float64, numpy=array([[5., 5.]])>

In [18]:
print(mat2)

tf.Tensor(
[[2.]
 [2.]], shape=(2, 1), dtype=float64)


In [19]:
print(tf.matmul(mat1,mat2))

tf.Tensor([[20.]], shape=(1, 1), dtype=float64)


In [20]:
print(mat1*mat2)

tf.Tensor(
[[10. 10.]
 [10. 10.]], shape=(2, 2), dtype=float64)
