In [1]:
# OM NAMAH SHIVAY

### 15-08-2022

# Numpy Library

## Numpy Arrays

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9,]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((3,))

array([0., 0., 0.])

In [17]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [18]:
np.zeros((3,0))

array([], shape=(3, 0), dtype=float64)

In [19]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.ones((3))

array([1., 1., 1.])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.linspace(0,5,1)

array([0.])

In [27]:
np.linspace(0,5,2)

array([0., 5.])

In [28]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [29]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [30]:
np.linspace(50,100,6)

array([ 50.,  60.,  70.,  80.,  90., 100.])

In [31]:
list2 = list(np.linspace(50,100,6))
list2

[50.0, 60.0, 70.0, 80.0, 90.0, 100.0]

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.eye(5,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.eye(1)

array([[1.]])

In [37]:
np.eye(0)

array([], shape=(0, 0), dtype=float64)

In [38]:
ar1 = np.eye(0)
ar1

array([], shape=(0, 0), dtype=float64)

In [39]:
ar1.shape

(0, 0)

In [40]:
arr.shape

(3,)

In [41]:
ar1 = ar1.reshape(10,0)

In [42]:
ar1

array([], shape=(10, 0), dtype=float64)

In [43]:
ar1.shape

(10, 0)

In [44]:
ar1

array([], shape=(10, 0), dtype=float64)

In [45]:
np.random.rand(4)

array([0.75494743, 0.83796941, 0.83772271, 0.87024507])

In [46]:
# Normal Distribution
np.random.randn(4)

array([ 0.23342418,  0.12791122, -1.10065644,  0.60645932])

In [47]:
np.random.rand(4,4)

array([[0.44688726, 0.524496  , 0.1038185 , 0.31628983],
       [0.17251468, 0.60860253, 0.88875276, 0.23026328],
       [0.74467907, 0.48457978, 0.93384698, 0.03350989],
       [0.63239755, 0.14080758, 0.31521063, 0.29896729]])

In [48]:
np.random.rand(4,2)

array([[0.28344877, 0.04872036],
       [0.34541541, 0.13661514],
       [0.74600627, 0.91460037],
       [0.36382895, 0.24992655]])

In [49]:
np.random.randn(2)

array([ 0.18674312, -0.28421372])

In [50]:
np.random.randn(2,3)

array([[ 0.38871028,  2.23688985, -0.37227731],
       [ 0.08624695,  0.97639007,  1.45136003]])

In [51]:
np.random.randint(0,2,8)

array([1, 1, 1, 1, 1, 0, 0, 0])

In [52]:
np.random.randint(12)

7

In [53]:
np.random.randint(1,100)

14

In [54]:
np.random.randint(1,100,3)

array([30, 55, 73])

In [55]:
arr = np.arange(25)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
ranarr = np.random.randint(0,50,10)

In [58]:
ranarr

array([28,  0,  0, 31, 35, 21, 25,  4, 43, 37])

In [59]:
arr.reshape(5,5) # 5 * 5 = 25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
ranarr

array([28,  0,  0, 31, 35, 21, 25,  4, 43, 37])

In [61]:
ranarr.max()

43

In [62]:
ranarr.min()

0

In [63]:
ranarr.argmax() # returns index of max

8

In [64]:
ranarr.argmin()

1

In [65]:
arr.shape

(25,)

In [66]:
arr = arr.reshape(5,5)

In [67]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
arr.shape

(5, 5)

In [69]:
lst = [31,3.2,32,1.1]

In [70]:
ar2 = np.array(lst)

In [71]:
ar2

array([31. ,  3.2, 32. ,  1.1])

In [72]:
ar2.dtype

dtype('float64')

In [73]:
lst = [31,3.2,32,1.1,'string',33]

In [74]:
np.array(lst)

array(['31', '3.2', '32', '1.1', 'string', '33'], dtype='<U32')

In [75]:
ar3 = np.array(lst)

In [76]:
ar3

array(['31', '3.2', '32', '1.1', 'string', '33'], dtype='<U32')

In [77]:
ar3.dtype

dtype('<U32')

In [78]:
ar3.shape

(6,)

In [79]:
ar3.reshape(3,2)

array([['31', '3.2'],
       ['32', '1.1'],
       ['string', '33']], dtype='<U32')

In [80]:
ar3 = ar3.reshape(3,2)

In [81]:
ar3.dtype

dtype('<U32')

In [82]:
arr.dtype

dtype('int32')

In [83]:
ranarr.dtype

dtype('int32')

In [84]:
from numpy.random import randint

In [85]:
randint(2,15)

7

## Numpy Array Indexing

In [86]:
arr = np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr[8]

8

In [89]:
arr[0]

0

In [90]:
arr[2:4]

array([2, 3])

In [91]:
arr[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [92]:
arr[0:9:2]

array([0, 2, 4, 6, 8])

In [93]:
arr[0:9:5]

array([0, 5])

In [94]:
arr[0:9:-1]

array([], dtype=int32)

In [95]:
arr[9:0:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [96]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [98]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr[::-2]

array([10,  8,  6,  4,  2,  0])

In [101]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [102]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [103]:
arr[::-2]

array([10,  8,  6,  4,  2,  0])

In [104]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr[0:4] = 100

In [106]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [107]:
slice_of_arr = arr[0:6]

In [108]:
slice_of_arr

array([100, 100, 100, 100,   4,   5])

In [109]:
slice_of_arr[2:]

array([100, 100,   4,   5])

In [110]:
slice_of_arr[:] 

array([100, 100, 100, 100,   4,   5])

In [111]:
slice_of_arr[:] = 99

In [112]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [113]:
# arr also gets updated along with slice_of_arr
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [114]:
arr_copy = arr.copy()

In [115]:
arr.copy()

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [116]:
arr_copy 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [117]:
arr_copy[::] = 909

In [118]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [119]:
arr_copy

array([909, 909, 909, 909, 909, 909, 909, 909, 909, 909, 909])

In [120]:
arr_2d = np.array([[5,4,3],[3,5,2],[52,2,6]])

In [121]:
arr_2d

array([[ 5,  4,  3],
       [ 3,  5,  2],
       [52,  2,  6]])

In [122]:
arr_2d[2]

array([52,  2,  6])

In [123]:
arr_2d[0]

array([5, 4, 3])

In [124]:
arr_2d[0][0]

5

In [125]:
arr_2d[2][1:]

array([2, 6])

In [126]:
arr_2d[0,2]

3

In [127]:
arr_2d[0,0]

5

In [128]:
arr_2d[0,1:]

array([4, 3])

In [129]:
arr_2d[2]

array([52,  2,  6])

In [130]:
arr_2d

array([[ 5,  4,  3],
       [ 3,  5,  2],
       [52,  2,  6]])

In [131]:
arr_2d[:2,1:]

array([[4, 3],
       [5, 2]])

In [132]:
arr_2d[:2]

array([[5, 4, 3],
       [3, 5, 2]])

In [133]:
arr_2d[1:]

array([[ 3,  5,  2],
       [52,  2,  6]])

In [134]:
arr = np.arange(1,11)

In [135]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [137]:
arr == 9

array([False, False, False, False, False, False, False, False,  True,
       False])

In [138]:
bool_arr = arr > 5

In [139]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [140]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [141]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [142]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [143]:
arr[arr<3]

array([1, 2])

In [144]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
arr_2d = np.arange(50)

In [146]:
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [147]:
arr_2d = np.arange(50).reshape(5,10)

In [148]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [149]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Numpy Operations

In [150]:
import numpy as np

In [151]:
arr = np.arange(0,11)

In [152]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [153]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [154]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [155]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [156]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [158]:
arr * .1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [159]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [160]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [161]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
arr / arr
# Error due to 0 present in the array and it is divided by zero
# 0/0 = nan 

C:\Users\Sid\AppData\Local\Temp\ipykernel_9476\468633097.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [163]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [164]:
arr / 0

C:\Users\Sid\AppData\Local\Temp\ipykernel_9476\3942562399.py:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0
C:\Users\Sid\AppData\Local\Temp\ipykernel_9476\3942562399.py:1: RuntimeWarning: invalid value encountered in divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [165]:
1

1

In [166]:
1/arr

C:\Users\Sid\AppData\Local\Temp\ipykernel_9476\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [167]:
# universal array

In [168]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [170]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [171]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [172]:
np.max(arr)

10

In [173]:
arr.max()

10

In [174]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [175]:
np.log(arr)

C:\Users\Sid\AppData\Local\Temp\ipykernel_9476\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [176]:
np.matrix([[3,3,1],[4,2,5]])

matrix([[3, 3, 1],
        [4, 2, 5]])

## Numpy Practice

In [177]:
import numpy as np

In [178]:
#1

In [179]:
z_arr = np.zeros(10)

In [180]:
print(z_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [181]:
#2

In [182]:
o_arr = np.ones(10)
print(o_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [183]:
# 3

In [184]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [185]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
arr = np.arange(10)

In [187]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [189]:
arr[:] = 5

In [190]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [191]:
# 4

In [192]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [193]:
# 5

In [194]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [195]:
np.arange(10,51) % 2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [196]:
arr = np.arange(10,51) 

In [197]:
arr[arr %2 == 0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [198]:
# 6

In [199]:
arr = np.arange(0,9)

In [200]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [201]:
# 7

In [202]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [203]:
np.random.randint(0,2,4)

array([0, 0, 1, 1])

In [204]:
np.random.randint(0,2)

1

In [205]:
np.random.rand(0,2)

array([], shape=(0, 2), dtype=float64)

In [206]:
np.random.randn(0,2)

array([], shape=(0, 2), dtype=float64)

In [207]:
np.random.rand(1)

array([0.38364824])

In [208]:
# 8

In [209]:
np.random.rand(25)

array([0.26959851, 0.31853971, 0.53081915, 0.60710355, 0.55283805,
       0.44921663, 0.44362163, 0.69457522, 0.47120846, 0.91889025,
       0.63592222, 0.66949177, 0.14539336, 0.13445676, 0.41832182,
       0.05625379, 0.03004236, 0.8808153 , 0.86047493, 0.91856679,
       0.89223011, 0.81759676, 0.97244393, 0.32375005, 0.63086734])

In [210]:
np.random.randn(25)

array([ 1.0817335 ,  0.59748403,  1.78464416, -0.19067328, -0.06352837,
        0.66178803, -0.92221759,  1.73485384, -0.68087879, -1.26953637,
        0.83550944,  0.76091651,  0.5596434 , -0.18519297, -0.37402798,
        0.86541074, -0.17323115, -1.11294634,  0.8579524 , -0.85953264,
        0.23685239, -1.48411895, -0.73128404,  1.57245217,  1.27827879])

In [211]:
# 9

In [212]:
np.arange(101) / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [213]:
arr = np.arange(1,101)

In [214]:
arr.shape

(100,)

In [215]:
arr.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [216]:
arr.reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [217]:
# 10

In [218]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [219]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [220]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [221]:
np.linspace(0,1,2250)

array([0.00000000e+00, 4.44642063e-04, 8.89284126e-04, ...,
       9.99110716e-01, 9.99555358e-01, 1.00000000e+00])

In [222]:
len(np.linspace(0,1,2250))

2250

In [223]:
# 11

In [224]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [225]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [226]:
mat[3,4]

20

In [227]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [228]:
mat[:3,1]

array([ 2,  7, 12])

In [229]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [230]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [231]:
mat[4]

array([21, 22, 23, 24, 25])

In [232]:
mat[-1]

array([21, 22, 23, 24, 25])

In [233]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [234]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [235]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [236]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [237]:
mat.sum()

325

In [238]:
np.sum(mat)

325

In [239]:
np.std(mat)

7.211102550927978

In [240]:
mat.std()

7.211102550927978

In [241]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [242]:
s=0
p=0
for item in mat:
    print(item[0])
    s += item
    p += item[0]
print(f's={s}')
print(f'p={p}')

1
6
11
16
21
s=[55 60 65 70 75]
p=55


In [243]:
mat[0]

array([1, 2, 3, 4, 5])

In [244]:
columns_sum = mat[0] + mat[1] + mat[2] + mat[3] + mat[4] # sum of all columns
columns_sum

array([55, 60, 65, 70, 75])

In [245]:
# sum of all columns
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [246]:
mat.sum(axis=0).sum()

325

In [247]:
mat.sum()

325

In [248]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [249]:
# sum of all rows
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

# How's that for Ultimate ?!