In [1]:
# OM NAMAH SHIVAY

# 15-08-2022

# 017 Numpy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9,]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((3,))

array([0., 0., 0.])

In [16]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [17]:
np.zeros((3,0))

array([], shape=(3, 0), dtype=float64)

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.ones((3))

array([1., 1., 1.])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [27]:
np.linspace(0,5,1)

array([0.])

In [28]:
np.linspace(0,5,2)

array([0., 5.])

In [29]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [30]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.eye(5,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.eye(1)

array([[1.]])

In [74]:
np.eye(0)

array([], shape=(0, 0), dtype=float64)

In [75]:
ar1 = np.eye(0)

In [77]:
ar1.shape

(0, 0)

In [78]:
arr.shape

(5, 5)

In [80]:
ar1 = ar1.reshape(10,0)

In [81]:
ar1

array([], shape=(10, 0), dtype=float64)

In [82]:
ar1.shape

(10, 0)

In [37]:
np.random.rand(4)

array([0.38737409, 0.62664025, 0.43944092, 0.39026003])

In [38]:
np.random.randn(4)

array([ 0.21317731, -0.28339296, -0.79975701, -2.28679061])

In [39]:
np.random.rand(4,4)

array([[0.41047043, 0.66338441, 0.9633169 , 0.55187261],
       [0.47162481, 0.07055906, 0.58686355, 0.64769526],
       [0.47398878, 0.29254383, 0.84464445, 0.94317268],
       [0.93328565, 0.57053332, 0.21399946, 0.64888733]])

In [40]:
np.random.rand(4,2)

array([[0.42692564, 0.91743021],
       [0.47068806, 0.12507889],
       [0.6371246 , 0.40141484],
       [0.18269899, 0.22718215]])

In [42]:
np.random.randn(2)

array([0.19964461, 0.65825585])

In [43]:
np.random.randn(2,3)

array([[ 1.60213332,  3.47121335,  1.09213725],
       [-0.50777688, -2.76349098, -0.73917602]])

In [45]:
np.random.randint(0,2,8)

array([1, 1, 0, 0, 1, 0, 0, 1])

In [46]:
np.random.randint(12)

11

In [47]:
np.random.randint(1,100)

90

In [48]:
np.random.randint(1,100,3)

array([23, 87, 56])

In [49]:
arr = np.arange(25)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
ranarr = np.random.randint(0,50,10)

In [52]:
ranarr

array([20, 32, 35, 31, 29, 42, 27, 36, 41, 45])

In [54]:
arr.reshape(5,5) # 5 * 5 = 25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
ranarr

array([20, 32, 35, 31, 29, 42, 27, 36, 41, 45])

In [58]:
ranarr.max()

45

In [59]:
ranarr.min()

20

In [61]:
ranarr.argmax() # returns index of max

9

In [62]:
ranarr.argmin()

0

In [64]:
arr.shape

(25,)

In [65]:
arr = arr.reshape(5,5)

In [66]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
arr.shape

(5, 5)

In [83]:
lst = [31,3.2,32,1.1]

In [84]:
ar2 = np.array(lst)

In [85]:
ar2

array([31. ,  3.2, 32. ,  1.1])

In [87]:
ar2.dtype

dtype('float64')

In [99]:
lst = [31,3.2,32,1.1,'string',33]

In [100]:
np.array(lst)

array(['31', '3.2', '32', '1.1', 'string', '33'], dtype='<U32')

In [101]:
ar3 = np.array(lst)

In [102]:
ar3

array(['31', '3.2', '32', '1.1', 'string', '33'], dtype='<U32')

In [103]:
ar3.dtype

dtype('<U32')

In [104]:
ar3.shape

(6,)

In [105]:
ar3.reshape(3,2)

array([['31', '3.2'],
       ['32', '1.1'],
       ['string', '33']], dtype='<U32')

In [106]:
ar3 = ar3.reshape(3,2)

In [107]:
ar3.dtype

dtype('<U32')

In [68]:
arr.dtype

dtype('int32')

In [71]:
ranarr.dtype

dtype('int32')

In [72]:
from numpy.random import randint

In [73]:
randint(2,15)

3

# 019 Numpy Array Indexing

In [110]:
arr = np.arange(0,11)

In [111]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
arr[8]

8

In [113]:
arr[0]

0

In [115]:
arr[2:4]

array([2, 3])

In [117]:
arr[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
arr[0:9:2]

array([0, 2, 4, 6, 8])

In [120]:
arr[0:9:5]

array([0, 5])

In [128]:
arr[0:9:-1]

array([], dtype=int32)

In [129]:
arr[9:0:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [122]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [123]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [124]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
arr[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
arr[::-2]

array([10,  8,  6,  4,  2,  0])

In [127]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [130]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
arr[0:4] = 100

In [132]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [133]:
slice_of_arr = arr[0:6]

In [134]:
slice_of_arr

array([100, 100, 100, 100,   4,   5])

In [136]:
slice_of_arr[2:]

array([100, 100,   4,   5])

In [137]:
slice_of_arr[:] 

array([100, 100, 100, 100,   4,   5])

In [138]:
slice_of_arr[:] = 99

In [139]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [144]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [145]:
arr_copy = arr.copy()

In [146]:
arr.copy()

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [147]:
arr_copy 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [149]:
arr_copy[::] = 909

In [150]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [152]:
arr_copy

array([909, 909, 909, 909, 909, 909, 909, 909, 909, 909, 909])

In [153]:
arr_2d = np.array([[5,4,3],[3,5,2],[52,2,6]])

In [154]:
arr_2d

array([[ 5,  4,  3],
       [ 3,  5,  2],
       [52,  2,  6]])

In [155]:
arr_2d[2]

array([52,  2,  6])

In [157]:
arr_2d[0]

array([5, 4, 3])

In [158]:
arr_2d[0][0]

5

In [159]:
arr_2d[2][1:]

array([2, 6])

In [160]:
arr_2d[0,2]

3

In [161]:
arr_2d[0,0]

5

In [162]:
arr_2d[0,1:]

array([4, 3])

In [165]:
arr_2d[2]

array([52,  2,  6])

In [166]:
arr_2d

array([[ 5,  4,  3],
       [ 3,  5,  2],
       [52,  2,  6]])

In [167]:
arr_2d[:2,1:]

array([[4, 3],
       [5, 2]])

In [168]:
arr_2d[:2]

array([[5, 4, 3],
       [3, 5, 2]])

In [169]:
arr_2d[1:]

array([[ 3,  5,  2],
       [52,  2,  6]])

In [171]:
arr = np.arange(1,11)

In [172]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [174]:
arr == 9

array([False, False, False, False, False, False, False, False,  True,
       False])

In [175]:
bool_arr = arr > 5

In [176]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [177]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [178]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [179]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [180]:
arr[arr<3]

array([1, 2])

In [181]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [182]:
arr_2d = np.arange(50)

In [183]:
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [184]:
arr_2d = np.arange(50).reshape(5,10)

In [185]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [186]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# 020 Numpy Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
arr * .1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [10]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [11]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr / arr

C:\Users\PC\AppData\Local\Temp\ipykernel_3560\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [16]:
arr / 0

C:\Users\PC\AppData\Local\Temp\ipykernel_3560\3942562399.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0
C:\Users\PC\AppData\Local\Temp\ipykernel_3560\3942562399.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [17]:
1

1

In [18]:
1/arr

C:\Users\PC\AppData\Local\Temp\ipykernel_3560\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [19]:
# universal array

In [20]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [23]:
np.max(arr)

10

In [24]:
arr.max()

10

In [25]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [26]:
np.log(arr)

C:\Users\PC\AppData\Local\Temp\ipykernel_3560\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [31]:
np.matrix([[3,3,1],[4,2,5]])

matrix([[3, 3, 1],
        [4, 2, 5]])

# 021-022 Numpy Practice

In [34]:
import numpy as np

In [38]:
#1

In [36]:
z_arr = np.zeros(10)

In [37]:
print(z_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [39]:
#2

In [41]:
o_arr = np.ones(10)
print(o_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
# 3

In [49]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr = np.arange(10)

In [56]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr[:] = 5

In [59]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [60]:
# 4

In [61]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [62]:
# 5

In [64]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [65]:
np.arange(10,51) % 2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [68]:
arr = np.arange(10,51) 

In [70]:
arr[arr %2 == 0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [72]:
# 6

In [74]:
arr = np.arange(0,9)

In [75]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
# 7

In [77]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.random.randint(0,2)

1

In [79]:
np.random.rand(0,2)

array([], shape=(0, 2), dtype=float64)

In [80]:
np.random.randn(0,2)

array([], shape=(0, 2), dtype=float64)

In [81]:
np.random.rand(1)

array([0.88124364])

In [82]:
# 8

In [83]:
np.random.rand(25)

array([0.22156326, 0.62085526, 0.3205734 , 0.98272868, 0.08473291,
       0.90918543, 0.85862257, 0.51925237, 0.1116021 , 0.63833236,
       0.84973324, 0.99373116, 0.19435283, 0.94937691, 0.88015922,
       0.78556886, 0.53891541, 0.60593628, 0.86257554, 0.2509842 ,
       0.36467105, 0.14946569, 0.18410265, 0.83398933, 0.79370193])

In [84]:
np.random.randn(25)

array([ 0.19964562,  0.81421643,  0.77244648,  0.60702066, -0.25662921,
        0.82796524,  1.12124136, -0.47703204,  1.54834403,  0.67117603,
        0.41618491, -0.82365444, -0.01093289,  0.23742726, -0.77696717,
        0.57022715, -1.6697319 , -0.26237689, -0.0355127 , -1.00818299,
        0.78241594, -1.20105664,  0.26664693, -1.28943026,  0.21535964])

In [85]:
# 9

In [87]:
np.arange(101) / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [95]:
arr = np.arange(1,101)

In [96]:
arr.shape

(100,)

In [97]:
arr.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [98]:
arr.reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [99]:
# 10

In [104]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [105]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [106]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [107]:
# 11

In [108]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [109]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [110]:
mat[3,4]

20

In [111]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [113]:
mat[:3,1]

array([ 2,  7, 12])

In [114]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [148]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [115]:
mat[4]

array([21, 22, 23, 24, 25])

In [149]:
mat[-1]

array([21, 22, 23, 24, 25])

In [116]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [150]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [151]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [117]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [119]:
mat.sum()

325

In [152]:
np.sum(mat)

325

In [153]:
np.std(mat)

7.211102550927978

In [121]:
mat.std()

7.211102550927978

In [122]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [126]:
for item in mat:
    print(item[0])

1
6
11
16
21


In [147]:
columns_sum = mat[0] + mat[1] + mat[2] + mat[3] + mat[4] # sum of all columns
columns_sum

array([55, 60, 65, 70, 75])

In [154]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# How's that for Ultimate ?!