# SciPy

SciPy is a collection of mathematical algorithms and convenience functions built on the Numpy extension of Python. It adds significant power to the interactive Python session by providing the user with high-level commands and classes for manipulating and visualizing data. With SciPy an interactive Python session becomes a data-processing and system-prototyping environment rivaling systems such as MATLAB, IDL, Octave, R-Lab, and SciLab.

The additional benefit of basing SciPy on Python is that this also makes a powerful programming language available for use in developing sophisticated programs and specialized applications. Scientific applications using SciPy benefit from the development of additional modules in numerous niches of the software landscape by developers across the world. 

Everything from parallel programming to web and data-base subroutines and classes have been made available to the Python programmer. All of this power is available in addition to the mathematical libraries in SciPy.


In [1]:
import numpy as np

from scipy import linalg
from scipy import sparse

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Linear Algebra
**linalg**

In [3]:
# Determinant of Matrix
linalg.det(A)

0.0

In [4]:
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
linalg.det(A)

3.0

Compute pivoted LU decomposition of a matrix.

The decomposition is::

    A = P L U

where P is a permutation matrix, L lower triangular with unit
diagonal elements, and U upper triangular.

In [5]:
P, L, U = linalg.lu(A)

P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [6]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [7]:
U

array([[7.        , 8.        , 8.        ],
       [0.        , 0.85714286, 1.85714286],
       [0.        , 0.        , 0.5       ]])

In [8]:
np.dot(L,U)

array([[7., 8., 8.],
       [1., 2., 3.],
       [4., 5., 6.]])

We can find out the eigenvalues and eigenvectors of this matrix:

In [9]:
EW, EV = linalg.eig(A)

EW

array([15.55528261+0.j, -1.41940876+0.j, -0.13587385+0.j])

In [10]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

Solving systems of linear equations can also be done:

In [11]:
v = np.array([[2],[3],[5]])
v

array([[2],
       [3],
       [5]])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [13]:
s = linalg.solve(A, v)
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

## Sparse Linear Algebra
SciPy has some routines for computing with sparse and potentially very large matrices. The necessary tools are in the submodule scipy.sparse.

construct a large matrix:

In [14]:
# Row-based linked list sparse matrix
A = sparse.lil_matrix((1000,1000))
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in List of Lists format>

In [15]:
A[0,:100]

<1x100 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in List of Lists format>

In [16]:
A[0,:100] = np.random.rand(100)
A[0,:100]

<1x100 sparse matrix of type '<class 'numpy.float64'>'
	with 100 stored elements in List of Lists format>

In [17]:
A[1, 100:200] = A[0,:100]

In [18]:
A.setdiag(np.random.rand(1000))

In [19]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in List of Lists format>

In [20]:
A[0,0]

0.5607453385544904

In [21]:
A[1,1]

0.07512036424595758

In [22]:
A[1,2]

0.0

In [23]:
A[0:3, :4]

<3x4 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in List of Lists format>

**Linear Algebra for Sparse Matrices**

In [24]:
from scipy.sparse import linalg

In [25]:
# Convert this matrix to Compressed Sparse Row format.
A.tocsc()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Column format>

In [26]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in List of Lists format>

In [27]:
A = A.tocsr()
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [28]:
b = np.random.rand(1000)

In [29]:
len(linalg.spsolve(A,b))

1000

In [30]:
linalg.spsolve(A,b)

array([ 1.96811190e+03, -1.42106376e+03,  2.87701924e-01,  8.80204726e-01,
        7.83177292e-01,  7.64910199e-01,  1.94096153e+01,  1.19035798e+00,
        1.29861006e+00,  4.10754104e+01,  1.20126505e+00,  4.55234333e+00,
        2.13644283e+00,  4.90380780e-01,  2.73729979e+00,  3.32939226e-01,
        9.08571751e-01,  1.00568558e-01,  5.91895294e-01,  1.95490011e-01,
        1.07554221e+00,  8.13359062e-01,  6.15318878e-01,  1.49676045e+00,
        4.43830188e+00,  3.12917035e-01,  5.97302758e-01,  1.07524846e+00,
        4.06888766e-01,  3.50765073e+00,  4.89056658e-01,  4.98987026e-01,
        6.22701662e-01,  1.30953413e+00,  3.37867140e-01,  9.89888201e+00,
        8.80190813e-01,  5.47388386e-01,  1.12199749e+00,  2.81821690e+00,
        4.40275688e-01,  2.95649463e-01,  2.36154280e+00,  1.98815244e-01,
        2.29341666e+00,  2.52438488e-01,  3.83283279e+00,  7.25663866e-01,
        8.78337446e-01,  1.41162453e+00,  1.99068901e+00,  4.26506723e-01,
        3.96299559e+00,  